###
# A simple Makefile for Lab #1
###

# define the java compiler to be used and the flags
JC = javac
FLAGS = -g -cp $(CP)
CP = .

# define the rules


# testing 
test:
	java -cp $(CP) Main

# clean up
clean:
	rm -f *~ *.class
